# Generated by Django 4.2.29 on 2026-03-14 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wardrobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Wardrobe', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('outerwear', 'Outerwear'), ('shoes', 'Shoes'), ('accessory', 'Accessory'), ('dress', 'Dress'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wardrobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.wardrobe')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
