# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_outfitrecord_wardrobe_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
